<?xml version="1.0"?>
<package format="2">
  <name>ladybug_bot_teleop</name>
  <version>0.1.0</version>
  <description>Keyboard teleop launch for driving Ladybug-Bot during mapping runs</description>
  <maintainer email="you@example.com">ranaariqi</maintainer>
  <license>MIT</license>

  <buildtool_depend>catkin</buildtool_depend>

  <depend>teleop_twist_keyboard</depend>
</package>
