<?xml version="1.0"?>
<package format="2">
  <name>ladybug_bot_description</name>
  <version>0.1.0</version>
  <description>URDF/xacro model of Ladybug-Bot, a 4-wheel differential drive mobile robot</description>
  <maintainer email="you@example.com">ranaariqi</maintainer>
  <license>MIT</license>

  <buildtool_depend>catkin</buildtool_depend>

  <depend>urdf</depend>
  <depend>xacro</depend>
  <depend>robot_state_publisher</depend>
  <depend>joint_state_publisher_gui</depend>
  <depend>rviz</depend>
</package>
