<?xml version="1.0"?>
<package format="2">
  <name>ladybug_bot_gazebo</name>
  <version>0.1.0</version>
  <description>Gazebo classic simulation world and spawn launch for Ladybug-Bot</description>
  <maintainer email="you@example.com">ranaariqi</maintainer>
  <license>MIT</license>

  <buildtool_depend>catkin</buildtool_depend>

  <depend>gazebo_ros</depend>
  <depend>ladybug_bot_description</depend>
</package>
